// <auto-generated />
namespace Simple_solutions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AdminContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdminContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201501081225462_AdminContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
